#!/usr/bin/env bash
# Display the list of currently running processes in a user-oriented format with hierarchy
#Must show all processes for all users including those which might not have a TTY

ps -a -x -u -f
