#!/usr/bin/env bash

# Trap SIGINT signal to display message
trap 'echo "Y U no love me?!"' SIGINT

# Trap SIGTERM signal to display message
trap 'echo "I hate the kill command";
rm -f /var/run/myscript.pid; exit 0' SIGTERM

# Trap SIGQUIT signal to terminate itself
trap 'rm -f /var/run/myscript.pid; exit 0'

# Get the PID of the script
echo $$ > /var/run/myscript.pid

# Display message indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 1
done
